### ISSUE TITLE
Je tu ešte niekto alebo sa o tohto bota už nestárate?

### ISSUE THREAD

**Issue by ghost** [vladantrhlik/wocabee-bot#10]
Ak by tu niekto bol, prijal by som nejakú pomoc, vyskúšal som všetko, išiel som krok po kroku v tom čo je v Issues a aj tak mi to nefunguje. Ak by na toto niekto odpovedal a bol by schopný pomôcť, tak by som poslal aj screen erroru.

**Comment by Bertik23** [comment]
Můžeš zkusit poslat chybu. Ale nezaručuju, že se nám povede ti pomoct. Vzhledem k tomu, že naše škola přestala Wocabee používat, tak už nemáme moc důvod se o bota starat.

**Comment by IDK1854** [comment]
@Bertik23 Já heslo neměnil :). Osobně mám tam na frontě 3 balíky, ale z vysoka na to seru. Ty učitelky si snad myslí že máme doma strašně moc času.... Zítra se na to zkusím podívat, jestli to stále funguje a napíšu, mohli to přes ty prázdniny nějak poladit.

**Comment by IDK1854** [comment]
@masterplayjegay Tak vypadá že to skvěle funguje.... Jen je potřeba mu trochu pomoct s tvorbou balíku. Jaký error tam máš?
@Bertik23 Kdyby jsi potřeboval pomoct s čímkoli ohledně arduina, tak neváhej mi napsat. Díky že se stále o to staráš. :)

**Comment by jacobsebek** [comment]
Bota udrzuju na
https://github.com/jacobsebek/wocabee-bot/tree/experimental

**Comment by jacobsebek** [comment]
A jestli to budeme pouzivat jeste dlouho, stejne ho prepisu, protoze sotva drzi pohromade. Jo a nezapomen pouzivat ten shell interface (python main.py), kdo vi jestli GUI jeste funguje, stejne je k nicemu.

**Comment by jacobsebek** [comment]
A protoze to HTML psal nejakej postizenej clovek, je dobra sance, ze to nerozjedes na Firefoxu, takze zkus Chrome nebo Edge.

**Comment by ghost** [comment]
Píše mi to toto -
![image](https://user-images.githubusercontent.com/91017948/135751694-bffed589-6c5c-4439-8906-c34e6246a0b8.png)
Skusil som fork aj @jacobsebek ale aj tak nefunguje.
Do toho browseru (Chromu) nijak nezasahujem, iba ho alt+tabnem aby som ho mohol ovladať cez konzolu
Slovíčka mám vo vzoru - Czech;Čeština

Neviem čo s tým urobiť. Predom ďakujem za odpoveď.

**Comment by IDK1854** [comment]
Máš správně pojmenovaný soubor? nazevbaliku.txt A nachází se v názvu balíku nějaké znaky kterými nelze pojmenovat soubor? Myslím tím např. / : nebo *.

**Comment by ghost** [comment]
Ano mám správne pomenovaný súbor, a nie, nie sú tam nejaké špecialné znaky.
![image](https://user-images.githubusercontent.com/91017948/135757152-38474812-aa56-441b-bc63-bb47b4429d63.png)

**Comment by jacobsebek** [comment]
Jo tak tuhle chybu jsem mel taky, jeste jsem to nepushnul, jde to opravit tak, ze na radku 229 zmenis `find_element_by_tag_name("a")` na `find_element_by_tag_name("i")`, AFAIK

**Comment by jacobsebek** [comment]
> Máš správně pojmenovaný soubor? nazevbaliku.txt A nachází se v názvu balíku nějaké znaky kterými nelze pojmenovat soubor? Myslím tím např. / : nebo *.

Mozna by stalo za to precist si ten error nez budes neco navrhovat :slightly_smiling_face:

**Comment by ghost** [comment]
Tak sorry, nevyznam sa do pythonu. :)
