### ISSUE TITLE
Jak nainstalovat Silenium?

### ISSUE THREAD

**Issue by IDK1854** [vladantrhlik/wocabee-bot#4]
čau, předem díky za skript, ale netuším jak nainstalovat Milenium pro desitky. Skript spoustim v Thony IDE a tam to po me chce milenium, kdyz zajdu na instalacni stranku s mileniem mam si nainstalovat python35 (jiz mam), a pote zadat do cmd C:\Python35\Scripts\pip.exe install selenium, cestu jsem zvolil spravnou ale v te slozce kde se mi nainstaloval python neni pip.exe, jedine python.exe. A ten nefunguje kdyz tam zadam. Diky za odpoved

**Comment by IDK1854** [comment]
![image](https://user-images.githubusercontent.com/77778963/105333934-91ab8c80-5bd6-11eb-906d-016114743c4c.png)

**Comment by IDK1854** [comment]
![image](https://user-images.githubusercontent.com/77778963/105353849-0dfe9980-5bf0-11eb-946a-f2ab29796d19.png)
Nebo taky tady: Velice rad bych to rozchodil :)))

**Comment by IDK1854** [comment]
![image](https://user-images.githubusercontent.com/77778963/105354079-58801600-5bf0-11eb-9469-0f3d4cfb0dd8.png)
Nebo taky Pycharm

**Comment by Bertik23** [comment]
Vzhledem k tomu, že sis účet na Githubu udělal dnes, tak předpokládám a neznáš pip, tak předpokládám, že se v pythonu moc neorientuješ.

1. pip najdeš v bys měl najít v `C:\Program Files\Python35\Scripts` ale obecně by mělo stačit napsat `pip`
2. Nainstaluj si všechny potřebnosti pomocí `pip install -r requirements.txt`
2. Spusť to z cmd nebo [terminálu](https://github.com/microsoft/terminal) pomocí `python ui.py`, abys měl jistotu, že se to spouští jak chceš
2. Můžeš zkusit spustit exečko z [1.2.beta.0](https://github.com/vladantrhlik/wocabee-bot/releases/tag/1.2.beta.0)

Je možný, že proběhl update wocabee, takže to nemusí fungovat. Ale mělo by.

**Comment by IDK1854** [comment]
Díky za odpověd, s python jsem teď začal na rpi po arduinu. Tím pádem nemám na PC žádné zkušenosti, uspesne jsem  nainstaloval requirements.txt, ale ted mi nejak nejde spustit viz foto.
Nejlepsi by fakt bylo to execko, akorat to kdyz spustim v chromu nebo edge vubec se nespusti, kdyz ho spustim do opery nebo do firefoxu tak uz to zacne neco delat, uspesne se prihlasim akorat jediny co jde trenovat baliky, u ostatnich moznosti (work, work %) to execko spadne a zustane bezet jen ten v prikaz v cmd. Takze to je asi beznadejne :/...
![image](https://user-images.githubusercontent.com/77778963/105421228-1253a280-5c42-11eb-865b-53311b4f5fcc.png)
EDIT: zkusil jsem si s tim trochu pohrat, zjistil jsem ze to nakonec funguje ale pokazde kdyz zapnu to execko tak muzu zvolit jen jednu moznost a pak kdyz zvolim druhou tak to spadne, tim myslim ze poprve zmacknu train udela to train a podruhe work a spadne program. work % nefunguji vubec. Kdyz poprve co zapnu program dam train, podruhe work tak se maximalne dostanu na nejakych 40%, pak to zase spadne/sam od sebe se zavre. Nvm jak tobe fungoval program.... Ani na ciste instalaci win 10, tam jsem pri prvnim zapnuti se dostal na 50% pak jiz jen na 40% a to mam do 31.1 udelat 8 celych baliku a nemam ani jeden :/. Mas discord nebo tak neco?

**Comment by vladantrhlik** [comment]
Ahoj, máš v nastavení wocabee nastavenou rychlost na tu nevyšší (5)? Myslím že defaultně je to na 3 a je možný že se nestihnou načíst všechny prvky.

**Comment by IDK1854** [comment]
> Ahoj, máš v nastavení wocabee nastavenou rychlost na tu nevyšší (5)? Myslím že defaultně je to na 3 a je možný že se nestihnou načíst všechny prvky.

Rychlost jsem snizil na 1 a poprve jsem se dostal na 50%, pak mi to spadlo viz. zde: https://streamable.com/tvpuub
Dale jak jsem to zkousel tak jsem se uz pres 50% nedostal, jen nejakych 23%, 36%, 19%, ani s mensim poctem slov se vysledek nezmenil...
Vyzkousel jsem vsechny ruzne prohlizece od IE po Firefox (krome Safari). :((

**Comment by Bertik23** [comment]
Ukazuje to nějakou chybovou hlášku, když to spadne? A mohl bys jí sem poslat?

**Comment by IDK1854** [comment]
> Ukazuje to nějakou chybovou hlášku, když to spadne? A mohl bys jí sem poslat?

Kdyz se to zavre, tak se neobjeví žádná chybová hláška, nebo nvm kde jí hledat. Maximálně tam byl jeden log z mozilly ten přikládám. 2x z 6 pokusů jsem se dostal alespoň na nějakých 50% ( tam podle mě chybí nějaký delay, když to zobrazí 50% je za mnou nebo nvm.) V souborech máš ještě log s tou lekcí, nvm jestli ti to nějak pomůže? Mám to zkusit na čisté instalaci win10?

[geckodriver.log](https://github.com/vladantrhlik/wocabee-bot/files/5862139/geckodriver.log)

**Comment by vladantrhlik** [comment]
Je dost možný že na wocabee jsou nějaký nový typy zkoušení, který v době kdy jsem to programoval ještě nebyly. Ve škole už wocabee nepoužíváme, takže to tam bohužel nemůžu přidat. Přidat další typy ale není nějak těžký, zkus si nejdřív udělat nějakej jednoduchej program se seleniem, a pak by to pro tebe neměl být problém.
https://github.com/vladantrhlik/wocabee-bot/blob/dc6070f6fb158fbf69a7e344de2e2d13b6e6923d/main.py#L125

**Comment by IDK1854** [comment]
> Je dost možný že na wocabee jsou nějaký nový typy zkoušení, který v době kdy jsem to programoval ještě nebyly. Ve škole už wocabee nepoužíváme, takže to tam bohužel nemůžu přidat. Přidat další typy ale není nějak těžký, zkus si nejdřív udělat nějakej jednoduchej program se seleniem, a pak by to pro tebe neměl být problém.
> https://github.com/vladantrhlik/wocabee-bot/blob/dc6070f6fb158fbf69a7e344de2e2d13b6e6923d/main.py#L125


Tak to bude trochu problém no... Až tak dobrej nejsem. Tak pro mě by nebyl problém ti poslat nick a heslo, to je to nejmenší, stačí mi abys tu napsal email nebo IG a já ti ho pošlu. My ještě budeme mít wocabee min. 5 let, jestli dříve neskončí. Co se mi tak zdá, že u některých slovíček přibylo napsání slovíčka co je na obrázku, ale schválně jsem tam dal balík na otestování kde nejsou obrázky. Ani moc nevím co tam přibylo, wocabee používám jenom 4 měsíce. Na druhou stranu jestli se ti to vůbec bude chtít dělat a jestli máš čas...

**Comment by IDK1854** [comment]
Zkoušel jsem to dále, přikládám foto z 6 pokusů, pokaždé to spadlo jinde. Neumím si to vysvětlit, proč tomu tak je. Jak již jsem psal nebyl by problém ti poslat přihlašovací jméno a heslo. Navíc mi ani nejde ten script v pythonu z nějakého důvodu vůbec spustit, jen ten exe soubor jde, ale ....
Díky za odpověď.

**Comment by IDK1854** [comment]
Už jsem celkem pokročil, ale pořád ten python script nelze z nějakého důvodu spustit. Používám python 3.5 a instaluji to dle tvého příkazu přímo z requirementsu. Přikládám logy jestli ti to nějak pomůže:
Na logu z NTB je python 3.5
Na logu z PC je python 3.9 (nejnovejsi)

[Log z NTB.txt](https://github.com/vladantrhlik/wocabee-bot/files/5875989/Log.z.NTB.txt)
[log z pc.txt](https://github.com/vladantrhlik/wocabee-bot/files/5876005/log.z.pc.txt)

**Comment by jacobsebek** [comment]
Oba dva tvoje errory se týkaj Qt, zkus to rozjet bez toho UI v konzoli, stačí spustit main.py a už tě to provede.

**Comment by IDK1854** [comment]
Díky za odpověď, už jsem vyzkoušel snad všechno, main.py funguje ale úplně stejný problém někde od 0% do 50% to prostě z nějakého důvodu spadne, vypadá to na bug v skripte, ale je divné proč na Linuxu Mint a Ubuntu nebo čisté instalaci win10 ( ano to všechno jsem již zkoušel, protože to, co zadává učitelka to je tak na hodinu práce denně ) mám úplně stejný výsledek. Dokonce se mi podařilo spustit na Linux Mint ui.py ale zase na nějakých 13% to spadne, pokaždé na jiném typu příkladu. Úplně stejný výsledek taky na betě 1.2 se spustitelným souborem .exe. 
Nevím jak u tebe funguje aktuálně wocabee bot ( jestli už ho nemáš stačí napsat ). Ještě přikládám nějaké obrázky a logy. Špatně se mi bude hledat bug v pythonu když jsem ledatak udělal 1 jednoduchý skript a to je všechno. Snad ten log z toho pomůže, ale již začínám ztrácet šanci že to vůbec pojede.


![Screenshot from 2021-01-27 14-47-30](https://user-images.githubusercontent.com/77778963/106063007-d9ab4180-60f7-11eb-97c6-693dfc37a416.png)

**Comment by jacobsebek** [comment]
Hele se spolužákem jsme měli podobný problémy takže já u sebe mám toho bota s pár změnama který to vyřešily, nechtěl jsem to uploadovat protože jsem to ani netestoval, ale můžeš si to teda stáhnout z branche "experimental" v mém forku, jestli to pomůže.
[Zde je link](https://github.com/jacobsebek/wocabee-bot/tree/experimental)

**Comment by IDK1854** [comment]
> Hele se spolužákem jsme měli podobný problémy takže já u sebe mám toho bota s pár změnama který to vyřešily, nechtěl jsem to uploadovat protože jsem to ani netestoval, ale můžeš si to teda stáhnout z branche "experimental" v mém forku, jestli to pomůže.
> [Zde je link](https://github.com/jacobsebek/wocabee-bot/tree/experimental)

No, bohužel ne. :((
Zkoušel jsem i zvýšit timeout, ale to taky bez změny.
Mám to ještě zkusit na jiných OS? Ale tak to je divné že vám to funguje a mi na Linuxu/Windowsech nefunguje.

**Comment by jacobsebek** [comment]
No ten pythonlog.txt napovídá, že to nemohlo najít ten typ otázky. Vždycky to spadne na určitym typu otázky nebo náhodně? To bych fakt potřeboval vědět. A taky mi ukaž ten trénovací soubor (název balíku.txt ve stejný složce jako main.py)

**Comment by IDK1854** [comment]
No před tím to bylo náhodně, jak se můžeš podívat na komentáři před 2 dněmi, ale s tvým experimentem se mi zdá že to padá na jednom typu (4x jsem to vyzkoušel) a spadlo to na stejném typu. Máš teamviewer?

**Comment by jacobsebek** [comment]
Nemám, přesně se v tom wocabee nevyznám ale jsem si docela jistej že tenhle typ úlohy je novej, je to tak @vladantrhlik @Bertik23 ?

**Comment by IDK1854** [comment]
Tak na to bych nikdy nepřišel že to je nový typ. A toto je asi taký nový typ co?

**Comment by jacobsebek** [comment]
No to je s těma obrázkama, jelikož by bylo trochu složitější rozeznávat obrázky tak to nefuguje. V mastru to přestane fungovat protože ten timer furt jede zatímco to nevyřešilo tu úlohu, ale v tom mym forku jsem to hotfixnul tak, že to prostě bude čekat dokud to sám nevyplníš.
EDIT:myslel jsem v mym "experimental"

**Comment by IDK1854** [comment]
> No to je s těma obrázkama, jelikož by bylo trochu složitější rozeznávat obrázky tak to nefuguje. V mastru to přestane fungovat protože ten timer furt jede zatímco to nevyřešilo tu úlohu, ale v tom mym forku jsem to hotfixnul tak, že to prostě bude čekat dokud to sám nevyplníš.

To by šlo no... V tvym experimentalu jsem to ještě nezkoušel, protože tam mám všechny balíky s tím vyplněné.

**Comment by jacobsebek** [comment]
Klidně bych ten novej typ implementoval (jestli to je fakt nový a nejsem blbej), ale asi bych potřeboval na testování pujčit účet, protože vlastní balíky vytvářet nemůžu ani nic takovýho.

**Comment by IDK1854** [comment]
> Klidně bych ten novej typ implementoval (jestli to je fakt nový a nejsem blbej), ale asi bych potřeboval na testování pujčit účet, protože vlastní balíky vytvářet nemůžu ani nic takovýho.

To je v pohodě napiš email nebo IG, nebo ti mám poslat prihlasovaci udaje na ten co jsem psal?

**Comment by jacobsebek** [comment]
jamertwo@gmail.com Sem mi posli prihlasovaci udaje

**Comment by IDK1854** [comment]
máš to tam :) kdyžtak pak napiš, kdyby jsi na něco přišel.

**Comment by jacobsebek** [comment]
Hele tak jsem naprogramoval ten novej typ otázky, zatím jsem to zkusil jen na "present continuous" první část a fungovalo to perfektně, chtěl jsem to co nejdřív pushnout, takže to můžeš stáhnout a vyzkoušet z 'experimental'

**Comment by IDK1854** [comment]
Tvl.. díky moc, ještě jedna otázka pokaždé co se dokončí trénování nebo work tak mě ten script spadne lépe řečeno vyskočí zpět do adresáře bez nějakého logu. Nevěděl by jsi co s tím?  tím myslím toto: 
vyberte balík (1-10): 4
co si přejete s tímto balíkem udělat? (1=procvičit(vytvořit txt), 2=nahnat body, 3=vypracovat(%)): 1
(po dokončení)
C:\Users\User\Desktop\

**Comment by jacobsebek** [comment]
Jo o tom vím, pro každou část toho balíku to prostě musíš celý restartovat

**Comment by IDK1854** [comment]
Ok, ani nevíš kolik si mi ušetřil času... No minimálně teď jsem nad tím strávil 4 hodiny jen s experimentováním na jakým os to pojede a jestli se to vůbec pustí a ty to máš hotový do 20 minut a ještě ti to funguje...

**Comment by IDK1854** [comment]
Šlo by tam nějak do toho skriptu zabudovat proměnné s loginem a heslem? popř. prohlížečem?

**Comment by jacobsebek** [comment]
Asi určitě, hele mám čas tak to jdu klidně udělat 😃

**Comment by jacobsebek** [comment]
Ok tak to bylo mnohem jednodušší než jsem si myslel, prostě jsem ten celej program dal do loopu. Když něco dokončíš tak to zase vypíše ty balíky atd. Restartovat musíš jenom kdybys měnil třídu. (stale v experimental)

**Comment by IDK1854** [comment]
No, program funguje dobře, ale občas tak co 2x pokus tam skočí nějaký error a aplikace spadne někde od 50% do 92% (opera hlásila že již slovo bylo zadáno nebo tak něco), padalo to i v minulé verzi, takže tím loopem to nebude. Více v logu:

[pythonlogcombinied (1).txt](https://github.com/vladantrhlik/wocabee-bot/files/5886907/pythonlogcombinied.1.txt)

**Comment by jacobsebek** [comment]
Ty "list out of range" errory se dějou kvůli tomu trénovacímu souboru. Musí být nějak rozbitej, tak mi je zase ukaž. U těch UnexpectedAlertPresentException vůbec nevim, děje se to i v jiných prohlížečích?

**Comment by IDK1854** [comment]
Spíše nerozumím tomu, proč jednou ten balík udělá a jednou ne. Ty UnexpectedAlertPresentException se dějí i v Chromu tak i v Opeře, v logu z minuleho komentare jsem přikládal dva errory jeden z Opery a jeden z Chromu. Odchytil jsem tu hlášku z opery asi po 5 pokusech viz obrazek. Taky jsem zkusil znovu vygenerovat Presnt tenses.txt jelo to 3x bez chyby a v chromu mě zase skočil UnexpectedAlertPresentException. Ale tak záleží jestli se ti to ještě chce řešit, mi to nějak aby to fungovalo stačí.
